import React, { useEffect } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";

// components libs
import Layout from "@/components/Layout";
import makeData from "@/libs/makeData";

const Table = dynamic(() => import("@/components/Table"), { ssr: false });

export default function Home() {
  const columns = React.useMemo(
    () => [
      {
        Header: "Item No",
        accessor: "itemno",
      },
      {
        Header: "Stock Code",
        accessor: "stockcode",
      },
      {
        Header: "Part No",
        accessor: "partno",
      },
      {
        Header: "Description",
        accessor: "description",
      },
      {
        Header: "Supplier A",
        columns: [
          {
            Header: "Quatity",
            accessor: "quantity",
          },
          {
            Header: "Price",
            accessor: "price",
          },
          ,
          {
            Header: "Lead Time",
            accessor: "leadtime",
          },
        ],
      },
      {
        Header: "Supplier B",
        columns: [
          {
            Header: "Quatity",
            accessor: "quantityb",
          },
          {
            Header: "Price",
            accessor: "priceb",
          },
          ,
          {
            Header: "Lead Time",
            accessor: "leadtimeb",
          },
        ],
      },
      {
        Header: "Supplier C",
        columns: [
          {
            Header: "Quatity",
            accessor: "quantityc",
          },
          {
            Header: "Price",
            accessor: "pricec",
          },
          ,
          {
            Header: "Lead Time",
            accessor: "leadtimec",
          },
        ],
      },
      {
        Header: "Result",
        accessor: "result",
      },
    ],
    []
  );

  const data = React.useMemo(() => makeData(20), []);

  return (
    <>
      <Head>
        <title>React Table</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          {" "}
          <Table columns={columns} data={data} />
        </Layout>
      </main>
    </>
  );
}
