import React, { useEffect } from "react";
import Head from "next/head";
import dynamic from "next/dynamic";

// components libs
import Layout from "@/components/Layout";
import makeData from "@/libs/makeData";

const Table = dynamic(() => import("@/components/Table"), { ssr: false });

export default function Home() {
  const columns = React.useMemo(
    () => [
      {
        Header: "Name",
        columns: [
          {
            Header: "First Name",
            accessor: "firstName",
          },
          {
            Header: "Last Name",
            accessor: "lastName",
          },
        ],
      },
      {
        Header: "Info",
        columns: [
          {
            Header: "Age",
            accessor: "age",
          },
          {
            Header: "Visits",
            accessor: "visits",
          },
          {
            Header: "Status",
            accessor: "status",
          },
          {
            Header: "Profile Progress",
            accessor: "progress",
          },
        ],
      },
    ],
    []
  );

  const data = React.useMemo(() => makeData(20), []);

  return (
    <>
      <Head>
        <title>React Table</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          {" "}
          <Table columns={columns} data={data} />
        </Layout>
      </main>
    </>
  );
}
